name: E2E Testing

on:
  push:
    branches:
      - master

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Execute tests
          uses: joonvena/robotframework-docker-action@v0.1
          env:
            BROWSER: chrome
            robot_tests_dir: ${{ github.workspace }}/tests
