name: Run test

on:
  push:
    branches: [ master ]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
        - run: pip install -r requirements.txt
        - name: Robot Framework
          uses: joonvena/robotframework-docker-action@v1.0
          with: 
            robot_tests_dir: ${{ github.workspace }}/tests/